import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { isLogin } from '../utils/auth';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {
  const router = useRouter();
  const isLoginUser = isLogin();

  useEffect(() => {
    if (!isLoginUser) {
      router.push('/login');
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>todo</main>
    </>
  );
}
